main: au.com.dylangonzalez.ultimatetag.UltimateTagPlugin
name: UltimateTag
version: 1.0.0
api-version: 1.16

commands:
  hello:
    description: Say hello!
    usage: /<hello>
  ultimatetag:
    description: Start an Ultimate Tag match between two players
    usage: /ultimatetag [start|restart] [<player> <player> | null]
  gui:
    description: Open up the custom GUI
    usage: /gui
